name: Snake Animation Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run the snake animation
      run: |
        echo "Rodando a animação da cobra"
        # Seu código de execução da animação ou outra tarefa
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} # Usando o token guardado nos secrets

    
